### ISSUE TITLE
Twitter upload sometimes fails

### ISSUE THREAD

**Issue by jason-curtis** [alanhussey/golden-hour#16]
I'm occasionally getting this error:

```
Traceback (most recent call last):
  File "/home/pi/.local/bin/golden-hour", line 11, in <module>
    load_entry_point('golden-hour', 'console_scripts', 'golden-hour')()
  File "/home/pi/golden-hour/golden_hour/main.py", line 138, in main
    media=timelapse_filename
  File "/home/pi/golden-hour/golden_hour/tweet.py", line 38, in post_update
    media_id = api.UploadMediaChunked(mediafile)
  File "/home/pi/.local/lib/python3.7/site-packages/twitter/api.py", line 1420, in UploadMediaChunked
    filename=filename)
  File "/home/pi/.local/lib/python3.7/site-packages/twitter/api.py", line 1353, in _UploadMediaChunkedAppend
    data=body_data)
  File "/home/pi/.local/lib/python3.7/site-packages/twitter/api.py", line 4919, in _RequestChunkedUpload
    raise TwitterError(str(e))
twitter.error.TwitterError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

Presumably this just happens because some kind of hiccup occurs during the long-ish process of uploading the video. Maybe we should add a retry, perhaps using [backoff](https://pypi.org/project/backoff/)?

**Comment by alanhussey** [comment]
Interesting, I don't think I've seen this before (and certainly not frequently). If it's due to upload time, do you think it's worth investigating tweaking the ffmpeg flags to get better compression?

**Comment by jason-curtis** [comment]
possibly. I've only seen this happen for sure, once. so I'll wait and see
if it happens again
